### ISSUE TITLE
Error when running `ts-router` template

### ISSUE THREAD

**Issue by jcmonnin** [amoutonbrady/vite-template-solid#4]
When running the unmodified template, I see some errors.

`About` page is empty, and there is an error on the console `Uncaught (in promise) ReferenceError: createEffect is not defined`. It looks like the `props` is a `Proxy` and gives an error when doing `JSON.stringify`. I don't understand what `about.data.ts` does. It doesn't seem to be used. Why is it exporting `HomeData` for the about page?

The `URL` on the top right is `undefined`. The editor complains about missing `router.location` property in `app.tsx`.

---
These are the commands I used
```
$ npx degit@2.8.0 amoutonbrady/vite-template-solid/ts-router my-solid-project
$ cd my-solid-project
$ pnpm install
$ pnpm run dev
```
Note that I had to downgrade degit; version 2.8.1 doesn't work for me. I believe this is linked to [this issue](https://github.com/Rich-Harris/degit/issues/273) and is independent of the template issue reported above.

**Comment by jcmonnin** [comment]
The about page can be fixed by replacing:
```
      <pre class="mt-4">
        <code>{JSON.stringify(props, null, 2)}</code>
      </pre>
```
with
```
      <pre class="mt-4">
        <code>{props.name}</code>
      </pre>
```
It looks like `JSON.stringify` doesn't work on a Proxy object

The top right URL can be fixed by replacing 

```
            <input
              class="w-75px p-1 bg-white text-sm rounded-lg"
              type="text"
              readOnly
              value={router.location}
            />
```
with
```
            <input
              class="w-75px p-1 bg-white text-sm rounded-lg"
              type="text"
              readOnly
              value={router[0].location}
            />
```

I'm still not sure how the `about.data.ts` is linked to the about page props, but I guess it is by file naming convention. This is more a `solid-app-router` question.

**Comment by amoutonbrady** [comment]
Thanks, I removed the auto-routing part in routes and updated the template to match the latest change in solid-app-router.
As per you `.data.ts` part, I reckon this is an undocumented feature of  `solid-app-router`. I'm thinking of making a small video to present the features soon. This might be helpful while we take proper time to write documentation there.

**Comment by jlmodell** [comment]
to fix this example you need to adjust the following:

### about.data.ts
first replace the import in _about.data.ts_, it looks like the type was updated and instead of ~~DataFn~~ it is now **RouteDataFunc**
\
++
<code>
import { RouteDataFunc } from "solid-app-router";
</code>

### about.tsx
you will need to import **useData** from solid-app-router which appears to be some kind of _hook_ to utilize the data passed to the route from your routing implementation.
\
(Perhaps in a prior iteration the data was passed to props instead of utilizing the useData _hook_  but there is no harm in leaving props in the function)
++
<code>
import { useData } from "solid-app-router"
</code>
\
\
then you will use the **useData** 'hook' to retrieve the data that was passed to the route in the route definition in _routes.ts_
++
<code>
const data = useData()
</code>
(_or destructured as_ <code>const { name } = useData()</code>)
\
\
and then finally replace the props with the data returned
\--
<code>{JSON.stringify(props,null,2}</code>
++
<code>{JSON.stringify(data,null,2}</code>
